### ISSUE TITLE
@timothygwebb You need to specify the work-directory keyword for each command. I have managed it to build successfully to the point you have.

### ISSUE THREAD

**Issue by timothygwebb** [boxbilling/boxbilling#693]
@timothygwebb You need to specify the work-directory keyword for each command. I have managed it to build successfully to the point you have.

```yaml
name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      working-directory: ./src

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: ./src/bb-vendor
        key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-    
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
      working-directory: ./src

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
    #     working-directory: ./src
```

_Originally posted by @samapraku in https://github.com/boxbilling/boxbilling/pull/691#issuecomment-717593637_

@samapraku thank you for your help now everyone's pull request submissions will test their composer.json and composer.lock. I will reject and request changes if the check fails. I am also thinking of implementing the Go Actions.
